fails:Thread#kill runs nested ensure clauses
fails:Thread#kill can be rescued by outer rescue clause when inner ensure clause raises exception
fails:Thread#kill is deferred if ensure clause does Thread.stop
fails:Thread#kill does not deadlock when called from within the thread while being joined from without
fails:Thread.kill causes the given thread to exit
